"""Add ibkr_perm_id to ibkr_orders

Revision ID: bd166037248f
Revises: a3221275ba50
Create Date: 2026-05-20 12:52:36.473078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd166037248f'
down_revision: Union[str, Sequence[str], None] = 'a3221275ba50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibkr_orders', sa.Column('ibkr_perm_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibkr_orders', 'ibkr_perm_id')
    # ### end Alembic commands ###
