"""initial schema

Revision ID: d3fd5db3b8ef
Revises: 
Create Date: 2026-05-06 07:20:55.838111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3fd5db3b8ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strategy_code', sa.String(length=50), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('symbol_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fill_model', sa.Enum('NEXT_BAR_OPEN', 'BAR_CLOSE', 'MIDPOINT', name='fill_model'), nullable=False),
    sa.Column('slippage_bps', sa.Integer(), nullable=False),
    sa.Column('commission_model', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backtest_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('PAPER', 'LIVE', name='portfolio_mode'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DISABLED', name='portfolio_status'), nullable=False),
    sa.Column('ibkr_account_code', sa.String(length=50), nullable=True),
    sa.Column('budget_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cash_reserved', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('cash_deployed', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('unrealized_pnl_cached', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget_total - cash_reserved - cash_deployed >= 0', name='ck_portfolio_cash_available_nonneg'),
    sa.CheckConstraint('budget_total > 0', name='ck_portfolio_budget_positive'),
    sa.CheckConstraint('cash_deployed >= 0', name='ck_portfolio_cash_deployed_nonneg'),
    sa.CheckConstraint('cash_reserved >= 0', name='ck_portfolio_cash_reserved_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('contract_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange', name='uq_symbol_ticker_exchange')
    )
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('drawdown_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trades', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('per_symbol_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_id')
    )
    op.create_table('historical_bars',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'ts', name='uq_bar_symbol_timeframe_ts')
    )
    op.create_index('ix_bar_symbol_timeframe_ts', 'historical_bars', ['symbol_id', 'timeframe', 'ts'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('ibkr_order_id', sa.Integer(), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('strategy_code', sa.String(length=50), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='order_side'), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('order_type', sa.Enum('MKT', 'LMT', name='order_type'), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', name='order_status'), nullable=False),
    sa.Column('order_ref', sa.String(length=255), nullable=False),
    sa.Column('reserved_cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty > 0', name='ck_order_qty_positive'),
    sa.CheckConstraint('reserved_cash >= 0', name='ck_order_reserved_cash_nonneg'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index(op.f('ix_orders_portfolio_id'), 'orders', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol_id'), 'orders', ['symbol_id'], unique=False)
    op.create_table('portfolio_symbol_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('strategy_code', sa.String(length=50), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allocation', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_code'], ['strategies.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol_id', name='uq_assignment_portfolio_symbol')
    )
    op.create_index(op.f('ix_portfolio_symbol_strategies_portfolio_id'), 'portfolio_symbol_strategies', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_symbol_strategies_symbol_id'), 'portfolio_symbol_strategies', ['symbol_id'], unique=False)
    op.create_table('virtual_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol_id', name='uq_vpos_portfolio_symbol')
    )
    op.create_index(op.f('ix_virtual_positions_portfolio_id'), 'virtual_positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_virtual_positions_symbol_id'), 'virtual_positions', ['symbol_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('ibkr_exec_id', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ibkr_exec_id')
    )
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('strategy_code', sa.String(length=50), nullable=False),
    sa.Column('strategy_version', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', 'EXIT', 'HOLD', name='signal_direction'), nullable=False),
    sa.Column('trigger_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_portfolio_id'), 'signals', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_signals_symbol_id'), 'signals', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_symbol_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_portfolio_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_virtual_positions_symbol_id'), table_name='virtual_positions')
    op.drop_index(op.f('ix_virtual_positions_portfolio_id'), table_name='virtual_positions')
    op.drop_table('virtual_positions')
    op.drop_index(op.f('ix_portfolio_symbol_strategies_symbol_id'), table_name='portfolio_symbol_strategies')
    op.drop_index(op.f('ix_portfolio_symbol_strategies_portfolio_id'), table_name='portfolio_symbol_strategies')
    op.drop_table('portfolio_symbol_strategies')
    op.drop_index(op.f('ix_orders_symbol_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_portfolio_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_bar_symbol_timeframe_ts', table_name='historical_bars')
    op.drop_table('historical_bars')
    op.drop_table('backtest_results')
    op.drop_table('symbols')
    op.drop_table('strategies')
    op.drop_table('portfolios')
    op.drop_table('backtests')
    # ### end Alembic commands ###
